### ISSUE TITLE
Concern about Code Release

### ISSUE THREAD

**Issue by haofanwang** [bytedance/DEADiff#1]
Thanks for your good work. I have a few concerns.

1. When will you release inference/training code? 
2. Why not train a SDXL version?
3. Is there a plan to release your dataset?

**Comment by Corleone-Huang** [comment]
The same concerns.

**Comment by Tianhao-Qi** [comment]
> Thanks for your good work. I have a few concerns.
> 
> 1. When will you release inference/training code?
> 2. Why not train a SDXL version?
> 3. Is there a plan to release your dataset?

Thanks for your interest in our work. We've included our replies to your concerns:
1. We'll release our inference code within this month.
2. DEADiff adapted to SDXL is in progress and will also be released.
3. We will release the detailed procedure of the dataset construction and are considering the form of releasing our dataset.

**Comment by loboere** [comment]
Another question, how much vram ram do you need?

**Comment by Tianhao-Qi** [comment]
> Another question, how much vram ram do you need?

You can refer to Table 5 in our paper:
<img width="405" alt="image" src="https://github.com/Tianhao-Qi/DEADiff_code/assets/37017794/bf9ad5a5-3d76-4a36-9805-7968992e7c85">

**Comment by akk-123** [comment]
@Tianhao-Qi  April is here, when will you release the code?
